databases:
  - name: platform-db
    plan: free
    databaseName: myhostingplatform

services:
  - type: web
    name: platform-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

  - type: static site
    name: platform-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    rewrites:
      - source: /*
        destination: /index.html
