services:
  # Service 1: The Backend API (Node.js)
  - type: web
    name: platform-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: platform-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: static site
          name: platform-frontend
          property: url
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          name: platform-api
          property: host

  # Service 2: The Frontend Dashboard (React Static Site)
  - type: static site
    name: platform-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    rewrites:
      - source: /*
        destination: /index.html

databases:
  # Service 3: The MongoDB Database
  - name: platform-db
    plan: free
    databaseName: myhostingplatform
