# render.yaml
# The correct configuration with persistent disks for uploads and deployments.

services:
  # The Backend API AND Frontend Server (Node.js/Express)
  - type: web
    name: webhosting- # Or whatever you named your web service
    env: node
    plan: free
    branch: main
    
    # Build and Start Commands
    buildCommand: "npm install"
    startCommand: "node server.js"
    
    # === PERSISTENT DISKS (CRITICAL FOR FILE UPLOADS) ===
    # This tells Render to create permanent storage and attach it to these paths.
    # The data in these folders will survive restarts and deploys.
    disks:
      - name: deployments
        mountPath: /opt/render/project/src/deployments
        sizeGB: 1
      - name: uploads
        mountPath: /opt/render/project/src/uploads
        sizeGB: 1
        
    # Environment Variables
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: platform-db # Must match the database name below
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Let Render create a secure secret
      - key: DOMAIN_NAME
        fromService:
          type: web
          name: webhosting- # MUST match the 'name' of this service
          property: host

# The Database (MongoDB)
databases:
  - name: platform-db
    plan: free
